# Generated by Django 4.0.2 on 2022-02-23 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_posts_following'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='datetime',
            new_name='dateandtime',
        ),
    ]
